import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Hero from '../components/Hero';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>RavenWest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Hero></Hero>
      <section>
        <h1 className='p-4 text-4xl'>Test</h1>
      </section>

      
    </>
  )
}
